name:                aoc2021
version:             0.1.0.0
github:              "hashedone/aoc2021"
license:             MIT
author:              "Bartłomiej `Hashed` Kuras"
copyright:           "Bartłomiej Kuras"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2021#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day1:
    main:                Main.hs
    source-dirs:         app/day1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
  day2:
    main:                Main.hs
    source-dirs:         app/day2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
    - parsec >= 3.1 && < 4
    - extra
